# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  user-service:
    build:
      context: .
      dockerfile: packages/user/Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./packages/user/src:/app/packages/user/src
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:example@mongodb:27017
      - PORT=4000
    depends_on:
      - mongodb

volumes:
  mongodb_data:
